<?php
$_['d_admin_menu'] = [
    'menu' => [
        0 => [
            'icon' => "fa-dashboard",
            'text' => "Dashboard",
            'link' => "index.php?route=common/dashboard&token=",
            'children' => [],
            'sort_order' => 0,
        ],
        1 => [
            'icon' => "fa-tags",
            'text' => "Catalog",
            'link' => "",
            'children' => [
                1 => [
                    'icon' => ">>",
                    'text' => "Categories",
                    'link' => "index.php?route=catalog/category&token=",
                    'children' => [],
                    'sort_order' => 1,
                ],
                2 => [
                    'icon' => ">>",
                    'text' => "Products",
                    'link' => "index.php?route=catalog/product&token=",
                    'children' => [],
                    'sort_order' => 2,
                ],
                3 => [
                    'icon' => ">>",
                    'text' => "Recurring Profiles",
                    'link' => "index.php?route=catalog/recurring&token=",
                    'children' => [],
                    'sort_order' => 3,
                ],
                4 => [
                    'icon' => ">>",
                    'text' => "Filters",
                    'link' => "index.php?route=catalog/filter&token=",
                    'children' => [],
                    'sort_order' => 4,
                ],
                5 => [
                    'icon' => ">>",
                    'text' => "Attributes",
                    'link' => "",
                    'children' => [
                        1 => ['icon' => ">>",
                            'text' => "Attributes",
                            'link' => "index.php?route=catalog/attribute&token=",
                            'children' => [],
                            'sort_order' => 1],
                        2 => ['icon' => ">>",
                            'text' => "Attribute Groups",
                            'link' => "index.php?route=catalog/attribute_group&token=",
                            'children' => [],
                            'sort_order' => 2],
                    ],
                    'sort_order' => 5,
                ],
                6 => [
                    'icon' => ">>",
                    'text' => "Options",
                    'link' => "index.php?route=catalog/option&token=",
                    'children' => [],
                    'sort_order' => 6,
                ],
                7 => [
                    'icon' => ">>",
                    'text' => "Manufactures",
                    'link' => "index.php?route=catalog/manufacturer&token=",
                    'children' => [],
                    'sort_order' => 7,
                ],
                8 => [
                    'icon' => ">>",
                    'text' => "Downloads",
                    'link' => "index.php?route=catalog/download&token=",
                    'children' => [],
                    'sort_order' => 8,
                ],
                9 => [
                    'icon' => ">>",
                    'text' => "Reviews",
                    'link' => "index.php?route=catalog/review&token=",
                    'children' => [],
                    'sort_order' => 9,
                ],
                10 => [
                    'icon' => ">>",
                    'text' => "Information",
                    'link' => "index.php?route=catalog/information&token=",
                    'children' => [],
                    'sort_order' => 10,
                ],

            ],
            'sort_order' => 1,
        ],
        2 => [
            'icon' => "fa-puzzle-piece",
            'text' => "Extensions",
            'link' => "",
            'children' => [
                0 => [
                    'icon' => ">>",
                    'text' => "Extension Installer",
                    'link' => "index.php?route=extension/installer&token=",
                    'children' => [],
                    'sort_order' => 0,
                ],
                1 => [
                    'icon' => ">>",
                    'text' => "Extensions",
                    'link' => "index.php?route=extension/extension&token=",
                    'children' => [],
                    'sort_order' => 1,
                ],
                2 => [
                    'icon' => ">>",
                    'text' => "Modifications",
                    'link' => "index.php?route=extension/modification&token=",
                    'children' => [],
                    'sort_order' => 2,
                ],
                3 => [
                    'icon' => ">>",
                    'text' => "Events",
                    'link' => "index.php?route=extension/event&token=",
                    'children' => [],
                    'sort_order' => 3,
                ],

            ],
            'sort_order' => 2,
        ],
        3 => [
            'icon' => "fa-television",
            'text' => "Design",
            'link' => "",
            'children' => [
                0 => [
                    'icon' => ">>",
                    'text' => "Layouts",
                    'link' => "index.php?route=design/layout&token=",
                    'children' => [],
                    'sort_order' => 0,
                ],
                1 => [
                    'icon' => ">>",
                    'text' => "Banners",
                    'link' => "index.php?route=design/banner&token=",
                    'children' => [],
                    'sort_order' => 1,
                ],
            ],
            'sort_order' => 3,
        ],
        4 => [
            'icon' => "fa-shopping-cart",
            'text' => "Sales",
            'link' => "",
            'children' => [
                0 => [
                    'icon' => ">>",
                    'text' => "Orders",
                    'link' => "index.php?route=sale/order&token=",
                    'children' => [],
                    'sort_order' => 0,
                ],
                1 => [
                    'icon' => ">>",
                    'text' => "Recurring Profiles",
                    'link' => "index.php?route=sale/recurring&token=",
                    'children' => [],
                    'sort_order' => 1,
                ],
                2 => [
                    'icon' => ">>",
                    'text' => "Recurring Profiles",
                    'link' => "index.php?route=sale/return&token=",
                    'children' => [],
                    'sort_order' => 2,
                ],
                3 => [
                    'icon' => ">>",
                    'text' => "Gift Vouchers",
                    'link' => "",
                    'children' => [
                        0 => [
                            'icon' => ">>",
                            'text' => "Gift Vouchers",
                            'link' => "index.php?route=sale/voucher&token=",
                            'children' => [],
                            'sort_order' => 0,
                        ],
                        1 => [
                            'icon' => ">>",
                            'text' => "Voucher Themes",
                            'link' => "index.php?route=sale/voucher_theme&token=",
                            'children' => [],
                            'sort_order' => 1,
                        ],
                    ],
                    'sort_order' => 3,
                ],
            ],
            'sort_order' => 4,
        ],
        5 => [
            'icon' => "fa-user",
            'text' => "Customers",
            'link' => "",
            'children' => [
                0 => [
                    'icon' => ">>",
                    'text' => "Customers",
                    'link' => "index.php?route=customer/customer&token=",
                    'children' => [],
                    'sort_order' => 0,
                ],
                1 => [
                    'icon' => ">>",
                    'text' => "Customer Groups",
                    'link' => "index.php?route=customer/customer_group&token=",
                    'children' => [],
                    'sort_order' => 1,
                ],
                2 => [
                    'icon' => ">>",
                    'text' => "Custom Fields",
                    'link' => "index.php?route=customer/custom_field&token=",
                    'children' => [],
                    'sort_order' => 2,
                ],
            ],
            'sort_order' => 5,
        ],
        6 => [
            'icon' => "fa-share-alt",
            'text' => "Marketing",
            'link' => "",
            'children' => [
                0 => [
                    'icon' => ">>",
                    'text' => "Marketing",
                    'link' => "index.php?route=marketing/marketing&token=",
                    'children' => [],
                    'sort_order' => 0,
                ],
                1 => [
                    'icon' => ">>",
                    'text' => "Affiliates",
                    'link' => "index.php?route=marketing/affiliate&token=",
                    'children' => [],
                    'sort_order' => 1,
                ],
                2 => [
                    'icon' => ">>",
                    'text' => "Coupons",
                    'link' => "index.php?route=marketing/coupon&token=",
                    'children' => [],
                    'sort_order' => 2,
                ],
                3 => [
                    'icon' => ">>",
                    'text' => "Mail",
                    'link' => "index.php?route=marketing/contact&token=",
                    'children' => [],
                    'sort_order' => 3,
                ],
            ],
            'sort_order' => 6,
        ],
        7 => [
            'icon' => "fa-cog",
            'text' => "System",
            'link' => "",
            'children' => [
                0 => [
                    'icon' => ">>",
                    'text' => "Settings",
                    'link' => "index.php?route=setting/store&token=",
                    'children' => [],
                    'sort_order' => 0,
                ],
                1 => [
                    'icon' => ">>",
                    'text' => "Users",
                    'link' => "",
                    'children' => [
                        0 => [
                            'icon' => ">>",
                            'text' => "Users",
                            'link' => "index.php?route=user/user&token=",
                            'children' => [],
                            'sort_order' => 0,
                        ],
                        1 => [
                            'icon' => ">>",
                            'text' => "User Groups",
                            'link' => "index.php?route=user/user_permission&token=",
                            'children' => [],
                            'sort_order' => 1,
                        ],
                        2 => [
                            'icon' => ">>",
                            'text' => "API",
                            'link' => "index.php?route=user/api&token=",
                            'children' => [],
                            'sort_order' => 2,
                        ],
                    ],
                    'sort_order' => 1,
                ],
                2 => [
                    'icon' => ">>",
                    'text' => "Localisation",
                    'link' => "",
                    'children' => [
                        0 => [
                            'icon' => ">>",
                            'text' => "Store Location",
                            'link' => "index.php?route=localisation/location&token=",
                            'children' => [],
                            'sort_order' => 0,
                        ],
                        1 => [
                            'icon' => ">>",
                            'text' => "Languages",
                            'link' => "index.php?route=localisation/language&token=",
                            'children' => [],
                            'sort_order' => 1,
                        ],
                        2 => [
                            'icon' => ">>",
                            'text' => "Currencies",
                            'link' => "index.php?route=localisation/currency&token=",
                            'children' => [],
                            'sort_order' => 2,
                        ],
                        3 => [
                            'icon' => ">>",
                            'text' => "Stock Statuses",
                            'link' => "index.php?route=localisation/stock_status&token=",
                            'children' => [],
                            'sort_order' => 3,
                        ],
                        4 => [
                            'icon' => ">>",
                            'text' => "Order Statuses",
                            'link' => "index.php?route=localisation/order_status&token=",
                            'children' => [],
                            'sort_order' => 4,
                        ],
                        5 => [
                            'icon' => ">>",
                            'text' => "Returns",
                            'link' => "",
                            'children' => [
                                0 => [
                                    'icon' => ">>",
                                    'text' => "Return Statuses",
                                    'link' => "index.php?route=localisation/return_status&token=",
                                    'children' => [],
                                    'sort_order' => 0,
                                ],
                                1 => [
                                    'icon' => ">>",
                                    'text' => "Return Actions",
                                    'link' => "index.php?route=localisation/return_action&token=",
                                    'children' => [],
                                    'sort_order' => 1,
                                ],
                                2 => [
                                    'icon' => ">>",
                                    'text' => "Return Reasons",
                                    'link' => "index.php?route=localisation/return_reason&token=",
                                    'children' => [],
                                    'sort_order' => 2,
                                ],
                            ],
                            'sort_order' => 5,
                        ],
                        6 => [
                            'icon' => ">>",
                            'text' => "Countries",
                            'link' => "index.php?route=localisation/country&token=",
                            'children' => [],
                            'sort_order' => 6,
                        ],
                        7 => [
                            'icon' => ">>",
                            'text' => "Zones",
                            'link' => "index.php?route=localisation/zone&token=",
                            'children' => [],
                            'sort_order' => 7,
                        ],
                        8 => [
                            'icon' => ">>",
                            'text' => "Geo Zones",
                            'link' => "index.php?route=localisation/geo_zone&token=",
                            'children' => [],
                            'sort_order' => 9,
                        ],
                        9 => [
                            'icon' => ">>",
                            'text' => "Taxes",
                            'link' => "",
                            'children' => [
                                0 => [
                                    'icon' => ">>",
                                    'text' => "Taxs Classes",
                                    'link' => "index.php?route=localisation/tax_class&token=",
                                    'children' => [],
                                    'sort_order' => 0,
                                ],
                                1 => [
                                    'icon' => ">>",
                                    'text' => "Tax Rates",
                                    'link' => "index.php?route=localisation/tax_rate&token=",
                                    'children' => [],
                                    'sort_order' => 1,
                                ],
                            ],
                            'sort_order' => 9,
                        ],
                        10 => [
                            'icon' => ">>",
                            'text' => "Length Classes",
                            'link' => "index.php?route=localisation/length_class&token=",
                            'children' => [],
                            'sort_order' => 10,
                        ],
                        11 => [
                            'icon' => ">>",
                            'text' => "Weight Classes",
                            'link' => "index.php?route=localisation/weight_class&token=",
                            'children' => [],
                            'sort_order' => 11,
                        ],
                    ],
                    'sort_order' => 2,
                ],
                3 => [
                    'icon' => ">>",
                    'text' => "Tools",
                    'link' => "",
                    'children' => [
                        0 => [
                            'icon' => ">>",
                            'text' => "Uploads",
                            'link' => "index.php?route=tool/upload&token=",
                            'children' => [],
                            'sort_order' => 0,
                        ],
                        1 => [
                            'icon' => ">>",
                            'text' => "Backup / Restore",
                            'link' => "index.php?route=tool/backup&token=",
                            'children' => [],
                            'sort_order' => 2,
                        ],
                        3 => [
                            'icon' => ">>",
                            'text' => "Error Logs",
                            'link' => "index.php?route=tool/log&token=",
                            'children' => [],
                            'sort_order' => 3,
                        ]
                    ],
                    'sort_order' => 3,
                ],
            ],


            'sort_order' => 7,
        ],
        8 => [
            'icon' => "fa-bar-chart-o",
            'text' => "Reports",
            'link' => "",
            'children' => [
                0 => [
                    'icon' => ">>",
                    'text' => "Sales",
                    'link' => "",
                    'children' => [
                        0 => [
                            'icon' => ">>",
                            'text' => "Orders",
                            'link' => "index.php?route=report/sale_order&token=",
                            'children' => [],
                            'sort_order' => 0,
                        ],
                        1 => [
                            'icon' => ">>",
                            'text' => "Tax",
                            'link' => "index.php?route=report/sale_tax&token=",
                            'children' => [],
                            'sort_order' => 1,
                        ],
                        2 => [
                            'icon' => ">>",
                            'text' => "Shipping",
                            'link' => "index.php?route=report/sale_shipping&token=",
                            'children' => [],
                            'sort_order' => 2,
                        ],
                        3 => [
                            'icon' => ">>",
                            'text' => "Returns",
                            'link' => "index.php?route=report/sale_return&token=",
                            'children' => [],
                            'sort_order' => 3,
                        ],
                        4 => [
                            'icon' => ">>",
                            'text' => "Coupons",
                            'link' => "index.php?route=report/sale_coupon&token=",
                            'children' => [],
                            'sort_order' => 4,
                        ]
                    ],
                    'sort_order' => 0,
                ],
                1 => [
                    'icon' => ">>",
                    'text' => "Products",
                    'link' => "",
                    'children' => [
                        0 => [
                            'icon' => ">>",
                            'text' => "Viewed",
                            'link' => "index.php?route=report/product_viewed&token=",
                            'children' => [],
                            'sort_order' => 0,
                        ],
                        1 => [
                            'icon' => ">>",
                            'text' => "Orders",
                            'link' => "index.php?route=report/product_purchased&token=",
                            'children' => [],
                            'sort_order' => 1,
                        ]
                    ],
                    'sort_order' => 1,
                ],
                2 => [
                    'icon' => ">>",
                    'text' => "Customers",
                    'link' => "",
                    'children' => [
                        0 => [
                            'icon' => ">>",
                            'text' => "Customers Online",
                            'link' => "index.php?route=report/customer_online&token=",
                            'children' => [],
                            'sort_order' => 0,
                        ],
                        1 => [
                            'icon' => ">>",
                            'text' => "Customer Activity",
                            'link' => "index.php?route=report/customer_activity&token=",
                            'children' => [],
                            'sort_order' => 1,
                        ],
                        2 => [
                            'icon' => ">>",
                            'text' => "Customer Searches",
                            'link' => "index.php?route=report/customer_search&token=",
                            'children' => [],
                            'sort_order' => 2,
                        ],
                        3 => [
                            'icon' => ">>",
                            'text' => "Orders",
                            'link' => "index.php?route=report/customer_order&token=",
                            'children' => [],
                            'sort_order' => 3,
                        ],
                        4 => [
                            'icon' => ">>",
                            'text' => "Reward Points",
                            'link' => "index.php?route=report/customer_reward&token=",
                            'children' => [],
                            'sort_order' => 4,
                        ],
                        5 => [
                            'icon' => ">>",
                            'text' => "Credit",
                            'link' => "index.php?route=report/customer_credit&token=",
                            'children' => [],
                            'sort_order' => 5,
                        ]
                    ],
                    'sort_order' => 2,
                ],
                3 => [
                    'icon' => ">>",
                    'text' => "Marketing",
                    'link' => "",
                    'children' => [
                        0 => [
                            'icon' => ">>",
                            'text' => "Marketing",
                            'link' => "index.php?route=report/marketing&token=",
                            'children' => [],
                            'sort_order' => 0,
                        ],
                        1 => [
                            'icon' => ">>",
                            'text' => "Affiliates",
                            'link' => "index.php?route=report/affiliate&token=",
                            'children' => [],
                            'sort_order' => 1,
                        ],
                        2 => [
                            'icon' => ">>",
                            'text' => "Affiliate Activity",
                            'link' => "index.php?route=report/affiliate_activity&token=",
                            'children' => [],
                            'sort_order' => 2,
                        ]
                    ],
                    'sort_order' => 3,
                ]

            ],
            'sort_order' => 8,
        ]

    ]
];
